version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - "./front:/app"
      - "/app/front/node_modules"

  back:
    build:
      context: ./back
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
